openapi: 3.0.0
info:
  title: 4FK Store API
  description:
    Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)
    or HTML.
  version: 1.0.0
servers:
  - url: http://localhost.com:{port}/api
    description: Local server
    variables:
      port:
        enum:
          - "5000"
        default: "5000"
        